# In your app's management/commands directory, create a new Python file, e.g., seed_projects.py
from django.core.management.base import BaseCommand
from ExclApp.models import project  # Ensure that 'Project' is correctly imported

class Command(BaseCommand):
    help = 'Seed projects data'

    def handle(self, *args, **kwargs):
        projects_data = [
            {
                'builder': 'Godrej',
                'project_name': 'Aqua',
                'project_type': 'Apartment',
                'project_size_acre': 2.15,
                'project_status': 'Completed',
                'possession_date': None,
                'unit_configuration_bhk': '2',
                'unit_size': 1098,
                'total_inventory': 540,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-aqua',
                'address': 'Godrej Aqua, Hosahalli, Bengaluru',
                'pin': '562157',
                'google_map': 'Godrej Aqua, Bangalore',
                'geo_imp': 'North'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Aqua',
                'project_type': 'Apartment',
                'project_size_acre': 2.15,
                'project_status': 'Completed',
                'possession_date': None,
                'unit_configuration_bhk': '3',
                'unit_size': 1442,
                'total_inventory': 540,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-aqua',
                'address': 'Godrej Aqua, Hosahalli, Bengaluru',
                'pin': '562157',
                'google_map': 'Godrej Aqua, Bangalore',
                'geo_imp': 'North'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Avenue',
                'project_type': 'Apartment',
                'project_size_acre': 5.3,
                'project_status': 'Completed',
                'possession_date': None,
                'unit_configuration_bhk': '1',
                'unit_size': 664,
                'total_inventory': 600,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-avenues',
                'address': 'Doddaballapur Main Rd, Sree Sai Layout, Bengaluru',
                'pin': '560064',
                'google_map': 'Godrej Avenues, Bangalore',
                'geo_imp': 'North'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Avenue',
                'project_type': 'Apartment',
                'project_size_acre': 5.3,
                'project_status': 'Completed',
                'possession_date': None,
                'unit_configuration_bhk': '2',
                'unit_size': 1259,
                'total_inventory': 600,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-avenues',
                'address': 'Doddaballapur Main Rd, Sree Sai Layout, Bengaluru',
                'pin': '560064',
                'google_map': 'Godrej Avenues, Bangalore',
                'geo_imp': 'North'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Avenue',
                'project_type': 'Apartment',
                'project_size_acre': 5.3,
                'project_status': 'Completed',
                'possession_date': None,
                'unit_configuration_bhk': '2.5',
                'unit_size': 1392,
                'total_inventory': 600,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-avenues',
                'address': 'Doddaballapur Main Rd, Sree Sai Layout, Bengaluru',
                'pin': '560064',
                'google_map': 'Godrej Avenues, Bangalore',
                'geo_imp': 'North'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Avenue',
                'project_type': 'Apartment',
                'project_size_acre': 5.3,
                'project_status': 'Completed',
                'possession_date': None,
                'unit_configuration_bhk': '3',
                'unit_size': 1525,
                'total_inventory': 600,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-avenues',
                'address': 'Doddaballapur Main Rd, Sree Sai Layout, Bengaluru',
                'pin': '560064',
                'google_map': 'Godrej Avenues, Bangalore',
                'geo_imp': 'North'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Athena',
                'project_type': 'Apartment',
                'project_size_acre': 6.5,
                'project_status': 'Ongoing',
                'possession_date': 'January 2028',
                'unit_configuration_bhk': '2',
                'unit_size': 854,
                'total_inventory': 330,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-athena',
                'address': '21, 7th Cross Rd, Jagadish Nagar, New Tippasandra, Bengaluru',
                'pin': '560075',
                'google_map': '21, 7th Cross Rd',
                'geo_imp': 'East'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Athena',
                'project_type': 'Apartment',
                'project_size_acre': 6.5,
                'project_status': 'Ongoing',
                'possession_date': 'January 2028',
                'unit_configuration_bhk': '3',
                'unit_size': 1103,
                'total_inventory': 330,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-athena',
                'address': '21, 7th Cross Rd, Jagadish Nagar, New Tippasandra, Bengaluru',
                'pin': '560075',
                'google_map': '21, 7th Cross Rd',
                'geo_imp': 'East'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Ananda Aerospace Park',
                'project_type': 'Apartment',
                'project_size_acre': 20.33,
                'project_status': 'Ongoing',
                'possession_date': 'August 2028',
                'unit_configuration_bhk': '2',
                'unit_size': 530,
                'total_inventory': 806,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-ananda',
                'address': 'Gummanahalli, Bengaluru',
                'pin': '562149',
                'google_map': 'Godrej Ananda, Bangalore',
                'geo_imp': 'East'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Ananda Aerospace Park',
                'project_type': 'Apartment',
                'project_size_acre': 20.33,
                'project_status': 'Ongoing',
                'possession_date': 'August 2028',
                'unit_configuration_bhk': '3',
                'unit_size': 701,
                'total_inventory': 806,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-ananda',
                'address': 'Gummanahalli, Bengaluru',
                'pin': '562149',
                'google_map': 'Godrej Ananda, Bangalore',
                'geo_imp': 'East'
            },
            {
                'builder': 'Godrej',
                'project_name': 'Splendour',
                'project_type': 'Apartment',
                'project_size_acre': 17.76,
                'project_status': 'Ongoing',
                'possession_date': 'September 2027',
                'unit_configuration_bhk': '2',
                'unit_size': 681,
                'total_inventory': 1165,
                'web': 'https://www.godrejproperties.com/bengaluru/residential/godrej-splendour',
                'address': 'Belathur Main Road, Belathur, Krishnarajapura, Bengalur',
                'pin': '560067',
                'google_map': 'Godrej Splendour, Whitefield Bangalore',
                'geo_imp': 'East'
            }
        ]

        for project_data in projects_data:
            project.objects.create(**project_data)
