# Generated by Django 5.0.4 on 2024-05-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder', models.CharField(choices=[('Shoba', 'Shoba')], max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_type', models.CharField(choices=[('Villas', 'Villas'), ('Apartment', 'Apartment'), ('Plots', 'Plots'), ('Villaments', 'Villaments'), ('Row Houses', 'Row Houses')], max_length=100)),
                ('project_status', models.CharField(choices=[('Delivered', 'Delivered'), ('OnGoing', 'OnGoing')], max_length=100)),
                ('configuration', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('geo_imp', models.CharField(blank=True, max_length=100, null=True)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('google_map', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
