# Generated by Django 5.0.4 on 2024-07-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExclApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='project',
            name='size',
        ),
        migrations.RemoveField(
            model_name='project',
            name='theme',
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='pin',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AddField(
            model_name='project',
            name='possession_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_size_acre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='total_inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='unit_configuration_bhk',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='unit_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='builder',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='geo_imp',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='google_map',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='web',
            field=models.URLField(default=0),
        ),
    ]
