# Generated by Django 5.0.4 on 2024-07-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExclApp', '0003_alter_project_total_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pin',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
